### PR TITLE
HTML Files will now work offline!

### PR DESCRIPTION
**Pull request by terminaltraces**
Changed the links within the documentation manually so that it can be used without a web server.

### CODE REVIEW

**Comment by terminaltraces** [comment]
Note that this is an emergency/temporary fix, if the files are regenerated the links will be lost.  Currently looking into alternate option.

**Comment by pearlchen** [comment]
@terminaltraces Is there a need for making the html branch offline at the moment? As you've noted, the next regeneration is going to just blast through your changes.

The solution lies somewhere in adding a `{{ baseurl }}` variable in front of any links that start with `/`. See http://ricostacruz.com/til/relative-paths-in-jekyll.html

I just haven't tested it yet. Do you want to take this on?

**Comment by pearlchen** [comment]
@terminaltraces Actually, I'm going to look into the baseurl thing right now...

**Comment by terminaltraces** [comment]
@pearlchen I can look into it later this week if you would like me to!  And yes, if you want to just avoid adding these changes until we do the real fix, that's fine.  I didn't know how quickly (for other events) offline documentation was needed, and I worked on it for a chunk of Friday - so I thought I might as well make the pull request.  :)

**Comment by pearlchen** [comment]
Baseurl fix submitted to jekyll branch to deal with CSS. Could you re-apply your patches to the jekyll branch, please? (Looks like you mostly changed anything that was /docs to a relative link, which is fine)

If there's a scenario in which you really want to use /docs, let me know what page it is so I can address specifics.

**Pull request closed without merging**
